xdescribe should be expect a function argument
Error: xdescribe expects a function argument; received [object Undefined] in /home/travis/build/chirimen-oh/WebGPIO/node_modules/jasmine-core/lib/jasmine-core/jasmine.js (line 934)
@/home/travis/build/chirimen-oh/WebGPIO/src/WebGPIO/interfaces/GPIOPort/GPIOPort.spec.js:66:3
@/home/travis/build/chirimen-oh/WebGPIO/src/WebGPIO/interfaces/GPIOPort/GPIOPort.spec.js:2:1